
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: ecapi_development

test:
  <<: *default
  database: ecapi_test

production:
  <<: *default
  database: <%= Rails.application.credentials.database['database'] %>
  username: <%= Rails.application.credentials.database['username'] %>
  password: <%= Rails.application.credentials.database['password'] %>
  host: <%= Rails.application.credentials.database['host'] %>
